# nginx/Dockerfile

# Use the official NGINX image from Docker Hub
FROM nginx:latest

# Copy custom nginx configuration file to NGINX's configuration directory
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to the outside world
EXPOSE 80

# Start NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]
